Feature('google');

Scenario('credit card', ({ I }) => {
    I.amOnPage('https://demo.midtrans.com/')
    I.click({ xpath: '//*[@id="container"]/div/div/div[1]/div[2]/div/div/a' })
    I.seeElement({ xpath: '//*[@id="container"]/div/div/div[2]/div[1]/div[1]/span[1]' })
    I.click({ xpath: '//*[@id="container"]/div/div/div[2]/div[2]/div[2]/img' })
    I.seeElement({ xpath: '//*[@id="container"]/div/div/div[2]/div[3]/div[1]/span' })
    I.click({ xpath: '//*[@id="main_setting_div_custom"]' })
    I.click({ xpath: '//*[@id="is_snap_pop_up:false"]' })
    I.scrollTo({ xpath: '//*[@id="main_setting_div_custom"]/div/div/div[5]/div[3]/label' })
    I.click({ xpath: '//*[@id="customselect"]' })
    I.seeCheckboxIsChecked({ xpath: '//*[@id="customselect"]' })
    I.click({ xpath: '//*[@id="enabled_payments:credit_card"]' })
    I.seeCheckboxIsChecked({ xpath: '//*[@id="enabled_payments:credit_card"]' })
    I.click({ xpath: '//*[@id="container"]/div/div/div[2]/div[3]/div[3]/div[2]/a' })
    I.wait(3)
    I.grabPopupText('credit/debit card')
    // I.grabPopupText('credit/debit card')
});
Scenario('ATM/Bank Transfer', ({ I }) => {
    I.amOnPage('https://demo.midtrans.com/')
    I.click({ xpath: '//*[@id="container"]/div/div/div[1]/div[2]/div/div/a' })
    I.seeElement({ xpath: '//*[@id="container"]/div/div/div[2]/div[1]/div[1]/span[1]' })
    I.click({ xpath: '//*[@id="container"]/div/div/div[2]/div[2]/div[2]/img' })
    I.seeElement({ xpath: '//*[@id="container"]/div/div/div[2]/div[3]/div[1]/span' })
    I.click({ xpath: '//*[@id="main_setting_div_custom"]' })
    I.scrollTo({ xpath: '//*[@id="main_setting_div_custom"]/div/div/div[5]/div[3]/label' })
    I.click({ xpath: '//*[@id="customselect"]' })
    I.seeCheckboxIsChecked({ xpath: '//*[@id="customselect"]' })
    I.click({ xpath: '//*[@id="enabled_payments:bank_transfer"]' })
    I.seeCheckboxIsChecked({ xpath: '//*[@id="enabled_payments:bank_transfer"]' })
    I.click({ xpath: '//*[@id="container"]/div/div/div[2]/div[3]/div[3]/div[2]/a' })
    I.wait(3)
    I.waitForText('Bank transfer')
});
Scenario('Gopay', ({ I }) => {
    I.amOnPage('https://demo.midtrans.com/')
    I.click({ xpath: '//*[@id="container"]/div/div/div[1]/div[2]/div/div/a' })
    I.seeElement({ xpath: '//*[@id="container"]/div/div/div[2]/div[1]/div[1]/span[1]' })
    I.click({ xpath: '//*[@id="container"]/div/div/div[2]/div[2]/div[2]/img' })
    I.seeElement({ xpath: '//*[@id="container"]/div/div/div[2]/div[3]/div[1]/span' })
    I.click({ xpath: '//*[@id="main_setting_div_custom"]' })
    I.scrollTo({ xpath: '//*[@id="main_setting_div_custom"]/div/div/div[5]/div[3]/label' })
    I.click({ xpath: '//*[@id="customselect"]' })
    I.seeCheckboxIsChecked({ xpath: '//*[@id="customselect"]' })
    I.click({ xpath: '//*[@id="enabled_payments:gopay"]' })
    I.seeCheckboxIsChecked({ xpath: '//*[@id="enabled_payments:gopay"]' })
    I.click({ xpath: '//*[@id="container"]/div/div/div[2]/div[3]/div[3]/div[2]/a' })
    I.wait(3)
    I.see('Gopay')
})
Scenario('Indomaret', ({ I }) => {
    I.amOnPage('https://demo.midtrans.com/')
    I.click({ xpath: '//*[@id="container"]/div/div/div[1]/div[2]/div/div/a' })
    I.seeElement({ xpath: '//*[@id="container"]/div/div/div[2]/div[1]/div[1]/span[1]' })
    I.click({ xpath: '//*[@id="container"]/div/div/div[2]/div[2]/div[2]/img' })
    I.seeElement({ xpath: '//*[@id="container"]/div/div/div[2]/div[3]/div[1]/span' })
    I.click({ xpath: '//*[@id="main_setting_div_custom"]' })
    I.scrollTo({ xpath: '//*[@id="main_setting_div_custom"]/div/div/div[5]/div[3]/label' })
    I.click({ xpath: '//*[@id="customselect"]' })
    I.seeCheckboxIsChecked({ xpath: '//*[@id="customselect"]' })
    I.click({ xpath: '//*[@id="enabled_payments:indomaret"]' })
    I.seeCheckboxIsChecked({ xpath: '//*[@id="enabled_payments:indomaret"]' })
    I.click({ xpath: '//*[@id="container"]/div/div/div[2]/div[3]/div[3]/div[2]/a' })
    I.wait(3)
    I.waitForText('Indomaret')
})
Scenario('CIMB Clicks', ({ I }) => {
    I.amOnPage('https://demo.midtrans.com/')
    I.click({ xpath: '//*[@id="container"]/div/div/div[1]/div[2]/div/div/a' })
    I.seeElement({ xpath: '//*[@id="container"]/div/div/div[2]/div[1]/div[1]/span[1]' })
    I.click({ xpath: '//*[@id="container"]/div/div/div[2]/div[2]/div[2]/img' })
    I.seeElement({ xpath: '//*[@id="container"]/div/div/div[2]/div[3]/div[1]/span' })
    I.click({ xpath: '//*[@id="main_setting_div_custom"]' })
    I.click({ xpath: '//*[@id="is_snap_pop_up:false"]' })
    I.scrollTo({ xpath: '//*[@id="main_setting_div_custom"]/div/div/div[5]/div[3]/label' })
    I.click({ xpath: '//*[@id="customselect"]' })
    I.seeCheckboxIsChecked({ xpath: '//*[@id="customselect"]' })
    I.click({ xpath: '//*[@id="enabled_payments:cimb_clicks"]' })
    I.seeCheckboxIsChecked({ xpath: '//*[@id="enabled_payments:cimb_clicks"]' })
    I.click({ xpath: '//*[@id="container"]/div/div/div[2]/div[3]/div[3]/div[2]/a' })
    I.wait(3)
    I.waitForText('OCTO Clicks')
}
);